tasks:
- command: >
    pip3 install -r requirements.txt &&
    wget https://github.com/gdrive-org/gdrive/releases/download/2.1.0/gdrive-linux-x64 &&
    mv gdrive-linux-x64 gdrive &&
    chmod +x gdrive
